version: '3.3'

services:
  # App config
  chat-backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:8080"
    expose:
      - "1234"
    restart: always
    extra_hosts:
      - localhost:127.0.0.1