version: '3.7'
services:
  openfire:
    build: .docker
    ports:
      - 9090:9090
      - 9091:9091
      - 5222:5222
      - 7777:7777
      - 7070:7070
    volumes:
      - openfire-data:/var/lib/openfire
      - data-logs:/var/log/openfire
    environment:
      DAEMON_OPTS: -Xms32m -Xmx128m -Xss128k -Xoss128k -XX:ThreadStackSize=128 -XX:+PrintGCDetails -Xloggc:/var/log/openfire/gc.log -XX:+HeapDumpOnOutOfMemoryError
volumes:
  openfire-data:
  data-logs: