version: '3.3'

services:
  # App config
  chat-backend-app:
    build:
      context: .
      dockerfile: AppDockerfile
    ports:
      - "1234:8080"
    expose:
      - "1234"
    restart: always
    extra_hosts:
      - localhost:127.0.0.1
    depends_on:
      - mysql-database
      - redis
    networks:
      - chatapp-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-database:3306/chat-realtime-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: chat-realtime-app
      SPRING_DATASOURCE_PASSWORD: dimagesharevn
      SPRING_REDIS.HOST: redis
      SPRING_REDIS.PORT: 6379

  # Database Service (Mysql)
  mysql-database:
    image: mysql:8
    ports:
      - "3309:3306"
    restart: always
    environment:
      MYSQL_DATABASE: chat-realtime-db
      MYSQL_USER: chat-realtime-app
      MYSQL_PASSWORD: Dimagesharevn&&2020
      MYSQL_ROOT_PASSWORD: r00t
    volumes:
      - db-data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
    networks:
      - chatapp-network
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-P", "3306", "-u", "root", "--password=root", "-e", "select 1", "DOCKERDB"]
      interval: 1s
      timeout: 3s
      retries: 30

  # Redis service
  redis:
    image: redis
    hostname: redis-host
    ports:
      - "6379:6379"
    command: [ "redis-server", "--protected-mode", "no" ]
    networks:
      - chatapp-network
    volumes:
      - redis-data:/var/lib/redis

  # Openfire service
  openfire:
    image: openfire
    build:
      context: .
      dockerfile: OpenFireDockerfile
    ports:
      - "3478:3478"
      - "3479:3479"
      - "5222:5222"
      - "5223:5223"
      - "5229:5229"
      - "5275:5275"
      - "5276:5276"
      - "5262:5262"
      - "5263:5263"
      - "7070:7070"
      - "7443:7443"
      - "7777:7777"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - openfire-lib:/var/lib/openfire
      - openfire-log:/var/log/openfire
    environment:
      DAEMON_OPTS: -Xms32m -Xmx128m -Xss128k -Xoss128k -XX:ThreadStackSize=128 -XX:+PrintGCDetails -Xloggc:/var/log/openfire/gc.log -XX:+HeapDumpOnOutOfMemoryError
    networks:
      - chatapp-network
    depends_on:
      - mysql-database


# Volumes
volumes:
  db-data:
  redis-data:
  openfire-lib:
  openfire-log:

# Networks to be created to facilitate communication between containers
networks:
  chatapp-network: