version: '3.3'
services:

  # Database Service (Mysql)
  mysql_database:
    image: mysql:8
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_DATABASE: chat-realtime-db
      MYSQL_USER: chat-app
      MYSQL_PASSWORD: dimagesharevn
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    networks:
      - chatapp-network

  # Openfire
  openfire:
    image: quantumobject/docker-openfire
    ports:
      - "9090:9090/tcp"
      - "9091:9091/tcp"
      - "5222:5222/tcp"
      - "7777:7777/tcp"
      - "7070:7070/tcp"
    volumes:
      - openfire-data:/var/lib/openfire
      - openfire-logs:/var/log/openfire
    links:
      - mysql_database
    depends_on:
      - mysql_database
    networks:
      - chatapp-network

  # Redis
  redis:
    image: "redis:alpine"
    hostname: redis-host
    ports:
      - "6379:6379"
    command: [ "redis-server", "--protected-mode", "no" ]
    networks:
      - chatapp-network
    volumes:
      - redis-data:/var/lib/redis

  # App config
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:8080"
    expose:
      - "1234"
    restart: always
    depends_on:
      - mysql_database
      - redis
    networks:
      - chatapp-network
    environment:
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/chat-realtime-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: chat-app
      SPRING_DATASOURCE_PASSWORD: dimagesharevn
      SPRING_DATASOURCE_PLATFORM: mysql
      SPRING_DATASOURCE_INITIALIZATION-MODE: always

      SPRING_JPA_DATABSE: mysql
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_HIBERNATE_DDL-AUTO: "none"
      SPRING_JPA_HIBERNATE_NAMING-STRATEGY: org.hibernate.cfg.ImprovedNamingStrategy
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL-STRATEGY: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      SPRING_JPA_HIBERNATE_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      SPRING_MAIN_ALLOW-BEAN-DEFINITION-OVERRIDING: "true"

      SPRING_REDIS_HOST: redis-host
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 1234
      SERVER_SERVLET_CONTEXT-PATH: /api
    extra_hosts:
      - localhost:127.0.0.1





volumes:
  db-data:
  openfire-data:
  openfire-logs:
  redis-data:
networks:
  chatapp-network: