version: '3.7'
services:
  openfire:
    links:
      - mysql_openfire
    depends_on:
      - mysql_openfire

  mysql_openfire:
    image: mysql
    volumes:
      - mysql_openfire-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-realtime-db
      MYSQL_USER: openfire
      MYSQL_PASSWORD: openfire
    ports:
      - 3309:3306
volumes:
  mysql_openfire-data: