spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_database:3309/chat-realtime-db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: chatapp-realtime
    password: dimagesharevn
    platform: mysql
    initialization-mode: always

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

  redis:
    host: localhost
    port: 6379

server:
  port: 1234
  servlet:
    context-path: /api

openfire:
  secret-key: F0Q8t0rOY8hhodIe
  host: localhost
  xmpp-client-connection-port: 5222
  xmpp-domain: dimagesharevn.develop

app:
  auth:
    token-secret: ZGltYWdlc2hhcmUtbGVnYWN5LWJhY2tlbmQtcHJvamVjdA==
    token-expiration-msec: 36000000