version: '3.7'
services:
  openfire:
    links:
      - mysql_openfire
    depends_on:
      - mysql_openfire

  mysql_openfire:
    image: mysql
    volumes:
      - ./data/mysql_openfire-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-realtime-db
      MYSQL_USER: chat-realtime-app
      MYSQL_PASSWORD: dimagesharevn
    ports:
      - 3309:3306
    networks:
      - chatapp-network

  # App config
  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:8080"
    expose:
      - "1234"
    restart: always
    depends_on:
      - mysql_openfire
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_openfire:3306/chat-realtime-db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: chat-realtime-app
      SPRING_DATASOURCE_PASSWORD: dimagesharevn
    networks:
      - chatapp-network
    extra_hosts:
      - localhost:127.0.0.1
networks:
  chatapp-network: